{
  "comments": [
    {
      "key": {
        "uuid": "ca3a3415_df6d2776",
        "filename": "cps-service/src/main/java/org/onap/cps/spi/exceptions/DataNodeAlreadyDefinedException.java",
        "patchSetId": 3
      },
      "lineNbr": 29,
      "author": {
        "id": 6862
      },
      "writtenOn": "2021-03-16T12:47:35Z",
      "side": 1,
      "message": "would prefer a unique one. This one is same as SchemaSetAlreadyDefinedException",
      "range": {
        "startLine": 29,
        "startChar": 49,
        "endLine": 29,
        "endChar": 68
      },
      "revId": "8dbece92e9a81385b0b2e0c4313916569a54004d",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    }
  ]
}